// <auto-generated />
namespace projectX.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class update_Case_and_Proects : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_Case_and_Proects));
        
        string IMigrationMetadata.Id
        {
            get { return "201809261322360_update_Case_and_Proects"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
